# Generated by Django 5.1.3 on 2024-11-25 15:19

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('anio', models.IntegerField()),
                ('semestre', models.BooleanField()),
                ('grupo', models.CharField(max_length=1, verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Organo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del organo')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('passhash', models.CharField(max_length=100, verbose_name='Hash')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Ayudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveldeacceso', models.CharField(max_length=5, verbose_name='Nivel de acceso')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('passhash', models.CharField(max_length=100, verbose_name='Hash')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('curso', models.ManyToManyField(blank=True, to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('Categoria', models.ManyToManyField(to='api.categoria')),
                ('curso', models.ManyToManyField(through='api.Lote', to='api.curso')),
                ('organo', models.ManyToManyField(blank=True, to='api.organo')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.muestra'),
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aumento', models.FloatField(blank=True, default=0.0, null=True)),
                ('name', models.CharField(default=api.models.default_name, max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to=api.models.generate_filename, verbose_name='Captura')),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.muestra')),
            ],
            options={
                'verbose_name': 'Captura',
                'verbose_name_plural': 'Capturas',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('passhash', models.CharField(max_length=100, verbose_name='Hash')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('curso', models.ManyToManyField(blank=True, to='api.curso')),
                ('permiso', models.ManyToManyField(blank=True, to='api.muestra')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profesor'),
        ),
        migrations.AddField(
            model_name='organo',
            name='sistema',
            field=models.ManyToManyField(blank=True, to='api.sistema'),
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=1500, verbose_name='Nota')),
                ('public', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.alumno')),
                ('ayudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ayudante')),
                ('muestra', models.ManyToManyField(blank=True, to='api.muestra')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profesor')),
                ('tags', models.ManyToManyField(blank=True, to='api.tag')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=1500, verbose_name='Nota')),
                ('coordenadas', models.JSONField(help_text='JSON con las coordenadas asociadas', verbose_name='Coordenadas')),
                ('tags', models.ManyToManyField(related_name='labels', to='api.tag', verbose_name='Etiquetas')),
            ],
        ),
        migrations.CreateModel(
            name='Tincion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('captura', models.ManyToManyField(blank=True, to='api.captura')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='tincion',
            field=models.ManyToManyField(blank=True, to='api.tincion'),
        ),
    ]
