# Generated by Django 5.0.6 on 2024-12-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captura',
            options={},
        ),
        migrations.RemoveField(
            model_name='captura',
            name='aumento',
        ),
        migrations.RemoveField(
            model_name='captura',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='tincion',
            name='captura',
        ),
        migrations.AddField(
            model_name='captura',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AlterField(
            model_name='captura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='captura',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='captura',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
