# Generated by Django 5.0.6 on 2024-12-14 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_captura_options_remove_captura_aumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captura',
            name='aumento',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='captura',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.muestra'),
        ),
    ]
