# Generated by Django 5.0.6 on 2024-12-15 06:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_captura_aumento_captura_muestra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captura',
            options={'verbose_name': 'Captura', 'verbose_name_plural': 'Capturas'},
        ),
        migrations.RemoveField(
            model_name='captura',
            name='preview',
        ),
        migrations.AlterField(
            model_name='captura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='captura',
            name='image',
            field=models.ImageField(upload_to=api.models.generate_filename, verbose_name='Captura'),
        ),
        migrations.AlterField(
            model_name='captura',
            name='name',
            field=models.CharField(blank=True, default=api.models.default_name, max_length=100),
        ),
    ]
