# Generated by Django 5.0.6 on 2024-12-16 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_notas_alumno_customuser_alumno_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='passhash',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='passhash',
        ),
    ]
