# Generated by Django 5.0.6 on 2024-12-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notas_alumno_alter_notas_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='cuerpo',
            field=models.TextField(default='text', verbose_name='Cuerpo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notas',
            name='titulo',
            field=models.CharField(default='text', max_length=255, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
