# Generated by Django 5.0.6 on 2024-12-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notas_cuerpo_notas_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='muestra',
        ),
        migrations.AddField(
            model_name='notas',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.muestra'),
        ),
    ]
