# Generated by Django 5.0.6 on 2024-12-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_notas_muestra_notas_muestra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='nota',
        ),
    ]
