# Generated by Django 5.0.6 on 2024-06-18 20:55

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('anio', models.IntegerField()),
                ('semestre', models.BooleanField()),
                ('grupo', models.CharField(max_length=1, verbose_name='Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('passhash', models.CharField(max_length=100, verbose_name='Hash')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='muestra',
            options={},
        ),
        migrations.RemoveField(
            model_name='muestra',
            name='image',
        ),
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to=api.models.generate_filename, verbose_name='Imagen')),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.muestra')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.AddField(
            model_name='muestra',
            name='Categoria',
            field=models.ManyToManyField(to='api.categoria'),
        ),
        migrations.CreateModel(
            name='Ayudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveldeacceso', models.CharField(max_length=5, verbose_name='Nivel de acceso')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('passhash', models.CharField(max_length=100, verbose_name='Hash')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('curso', models.ManyToManyField(to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('passhash', models.CharField(max_length=100, verbose_name='Hash')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('permiso', models.ManyToManyField(to='api.muestra')),
                ('curso', models.ManyToManyField(to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curso')),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.muestra')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='curso',
            field=models.ManyToManyField(through='api.Lote', to='api.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profesor'),
        ),
    ]
