# Generated by Django 5.0.6 on 2024-07-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=100, verbose_name='Nombre del organo')),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisname', models.CharField(max_length=100, verbose_name='Nombre del sistema')),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='organo',
            field=models.ManyToManyField(to='api.organo'),
        ),
        migrations.AddField(
            model_name='organo',
            name='sistema',
            field=models.ManyToManyField(to='api.sistema'),
        ),
    ]
