# Generated by Django 5.0.6 on 2024-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organo_sistema_muestra_organo_organo_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.ManyToManyField(blank=True, null=True, to='api.curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='permiso',
            field=models.ManyToManyField(blank=True, null=True, to='api.muestra'),
        ),
        migrations.AlterField(
            model_name='ayudante',
            name='curso',
            field=models.ManyToManyField(blank=True, null=True, to='api.curso'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='organo',
            field=models.ManyToManyField(blank=True, null=True, to='api.organo'),
        ),
        migrations.AlterField(
            model_name='organo',
            name='sistema',
            field=models.ManyToManyField(blank=True, null=True, to='api.sistema'),
        ),
    ]
